# FOR DEVELOPMENT PURPOSES ONLY – see hard-coded database credentials!

services:
  web:
    build: .
    ports:
        # http server
      - "8000:8000"
        # web socket server that remix uses for development
      - "8002:8002"
        # prisma studio, which can be run with `docker exec` when needed
      - "5555:5555"
    entrypoint:
      - sh
      - scripts/entrypoint_dev.sh
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    links:
      - db
    environment:
      DATABASE_URL: postgresql://app:app@db/app
      STUDENT_DATA: ${STUDENT_DATA}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      SECRET_KEY: anything
    # Prisma is broken on arm; see https://github.com/prisma/prisma/issues/10761
    platform: linux/amd64
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app

volumes:
  node_modules:
